config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  resources :terraces, only: [ :index, :show, :create, :new, :destroy ] do
    resources :bookings, only: [ :create, :new ]
  end

  resources :bookings, only: [ :index, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # include ActiveModel::Validations

  belongs_to :user
  belongs_to :terrace

  # TEST STATUS=AVAILABILITY

  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date

  def booked_date_range
    { from: :start_date, to: :end_date }
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/terrace.rb
class Terrace < ApplicationRecord
  belongs_to :user
  has_many :bookings

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: :address,
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :terraces, dependent: :destroy
  has_many :bookings
  has_one_attached :avatar
end

app/controllers/application_controller.rb
require 'date'

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @terraces = Terrace.all
    @user = current_user

  end

  def new
    @terrace = Terrace.find(params[:terrace_id])
    @booking = Booking.new
    @user = current_user
  end

  def create
    @terrace = Terrace.find(params[:terrace_id])
    # start_date = Date.new(booking_params['start_date(1i)'].to_i, bookusering_params['start_date(2i)'].to_i, booking_params['start_date(3i)'].to_i)
    # end_date = Date.new(booking_params['end_date(1i)'].to_i, booking_params['end_date(2i)'].to_i, booking_params['end_date(3i)'].to_i)
    @booking = Booking.new(booking_params)
    @booking.terrace = @terrace
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @terrace = Terrace.new
    @terraces = Terrace.all
  end
end

app/controllers/terraces_controller.rb
class TerracesController < ApplicationController
  def index
    @terraces = Terrace.all
    if params[:query].present?
      @terraces = @terraces.search_by_address(params[:query])
    end

    @terraces = @terraces.geocoded
    @markers = @terraces.map do |terrace|
      {
        lat: terrace.latitude,
        lng: terrace.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { terrace: terrace }),
        image_url: helpers.asset_url('parasol.png')
      }
    end
    @user = current_user
  end

  def show
    @terrace = Terrace.find(params[:id])
    @booking = Booking.new
    @user = current_user

    @terraces = Terrace.geocoded.find(params[:id])
    @markers =
      [{
        lat: @terraces.latitude,
        lng: @terraces.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { terrace: @terraces }),
        image_url: helpers.asset_url('parasol.png')
      }]
  end

  def new
    @terrace = Terrace.new
  end

  def create
    @terrace = Terrace.new(terrace_params)
    @terrace.user_id = current_user.id
    if @terrace.save!
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @user = current_user
    @terrace = Terrace.find(params[:id])
    @terrace.destroy
    redirect_to bookings_path
  end

  private

  def terrace_params
    params.require(:terrace).permit(:name, :description, :photo, :address, :price_per_night)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def edit, update, new, create, and delete are already created by devise
  def show
    @user = User.find(params[:id])
  end

  def host

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-second">
  <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <div class="nav-sec-item">
        <li>
          <%= link_to "Host a terrace", new_terrace_path, class: "nav-sec-link" %>
        </li>
      </div>
      <div class="nav-sec-item">
        <li>
          <%= link_to "Book a terrace", root_path, class: "nav-sec-link" %>
        </li>
      </div>
      <% if !user_signed_in? %>
        <div class="nav-sec-item">
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-sec-link" %>
          </li>
        </div>
        <div class='nav-sec-item'>
          <li>
            <%= link_to "Log in", user_session_path, class: "nav-sec-link" %>
          </li>
        </div>
      <% else %>
        <li class="nav-item dropdown d-flex align-items-center ml-3">
          <% if @user.avatar.attached? %>
            <img src="<%= (url_for(current_user.avatar)) %>" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true aria-expanded=false >
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My dashboard", bookings_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <nav>
    <div class="nav nav-tabs onglets d-flex justify-content-center" id="nav-tab" role="tablist">
      <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">My terraces</a>
      <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">My bookings</a>
    </div>
  </nav>
</div>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

    <div class="container">
      <h2 class="mt-4"> List of your terraces</h2>

        <% @terraces.each do |terrace| %>
          <% if terrace.user_id == current_user.id %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(terrace.photo.key) %>')">
              <div class="text-booking">
                <h5><%= terrace.name %></h5>
                <p><strong><%= terrace.price_per_night %></strong> €</p>
                <p><em><%= terrace.description %></em></p>
                <p><%= terrace.address %></p>
              <div class="d-flex justify-content-center mt-3">
                <%= link_to icon('fas', 'trash'), terrace_path(terrace),
                    method: :delete,
                    data: { confirm: "Are you sure?" }, class:"icon-trash" %>
              </div>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>

  </div>
  <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

    <div class="container">
      <h2 class="mt-4"> List of your reservations </h2>

      <% @bookings.each do |booking| %>
        <% if booking.user_id == current_user.id %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(booking.terrace.photo.key) %>')">
            <div class="text-booking">
              <h5><%= booking.terrace.name %></h5>
              <p><em><%= booking.start_date %> –– <%= booking.end_date %></em></p>
              <p><strong><%= ((booking.end_date - booking.start_date).to_i) * booking.terrace.price_per_night %>€ </strong></p>
              <p><%= booking.terrace.address %></p>
              <div class="d-flex justify-content-center">
                <% j_minus = (booking.start_date - Date.today).to_i  %>
                <button type="button" class="mt-3 btn btn-outline-light btn-toggle-date" data-toggle="popover" data-placement="right"
                data-content=" <% if booking.start_date > Date.today %>
                                    J - <%= j_minus  %> days !
                                <% elsif %>
                                  <% booking.start_date < Date.today && Date.today < booking.end_date %>
                                  <%= "happening .." %>
                                <% else %>
                                  <%= "already done, hope you enjoyed your stay !" %>
                                <% end %>">

                  <i class="far fa-clock"></i>
                </button>
              </div>
              <div class= "d-flex justify-content-center mt-2">
                <%= link_to icon('fas', 'trash'), booking_path(booking),
                    method: :delete,
                    data: { confirm: "Are you sure?" }, class:"icon-trash" %>
              </div>
            </div>
          <% end %>
        </div>
        <% end %>
        </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rent My Sun</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <%= yield %>

    <div class="footer">
      <div class="footer-copyright">
        © 2020 Sun-For-Rent, Inc. All rights reserved
      </div>
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class= "banner">
  <div class="navbar navbar-home navbar-expand-sm navbar-light fixed-top">
    <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Host a terrace", user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Host a terrace", new_terrace_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <img src="<%= (url_for(current_user.avatar)) %>" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true aria-expanded=false >
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My dashboard", bookings_path, class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <%= image_tag "Background.jpg", class: "img-background" %>

  <div class="container-sm d-flex justify-content-center">
    <div class="row">
      <div class="search-form col-sm-12 offset-sm-4">
        <div class="card search">
          <div class= "d-flex justify-content-center">
            <h2>Book unique terraces to enjoy</h2>
          </div>
            <%= simple_form_for :terrace, url: terraces_path, method: :get do |f| %>
              <%= f.input :address, name: "search[query]" %>
              <div class= "d-flex justify-content-center">
              <%= f.submit 'search', class: 'btn btn-primary' %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-5">
  <h2 class="mt-5 carousel-title">Best terraces of the world</h2>
</div>

<div class="container-sm container-carousel">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="2500">
    <div class="carousel-inner">
      <div class="carousel-item active ml-2 ">
        <div class="d-flex justify-content-center">
          <div class="card carousel shadow mb-3 w-75">
            <div class="row no-gutters">
              <% terrace = @terraces.sample %>
              <div class="col-md-4">
                <%= cl_image_tag terrace.photo.key, class: "card-img carousel" %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to terrace.name, terrace_path(terrace) %></h5>
                  <p class="card-text carousel"><%= terrace.description %></p>
                <p class="card-text carousel"><%= terrace.price_per_night %>€ per night</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="carousel-item ml-2">
        <div class="d-flex justify-content-center">
          <div class="card carousel shadow mb-3 d-block w-75">
            <div class="row no-gutters">
              <% terrace = @terraces.sample %>
              <div class="col-md-4">
                <%= cl_image_tag terrace.photo.key, class: "card-img carousel" %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to terrace.name, terrace_path(terrace) %></h5>
                  <p class="card-text carousel"><%= terrace.description %></p>
                <p class="card-text carousel"><%= terrace.price_per_night %>€ per night</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="carousel-item ml-2">
        <div class="d-flex justify-content-center">
          <div class="card carousel shadow mb-3 d-block w-75">
            <div class="row no-gutters">
              <% terrace = @terraces.sample %>
              <div class="col-md-4">
                <%= cl_image_tag terrace.photo.key, class: "card-img carousel" %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to terrace.name, terrace_path(terrace) %></h5>
                  <p class="card-text carousel"><%= terrace.description %></p>
                <p class="card-text carousel"><%= terrace.price_per_night %>€ per night</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/terraces/_info_window.html.erb
<div id="map-photo-display">
  <%= cl_image_tag terrace.photo.key, id: "map-photo" %>
</div>
<h5 class="mt-2"><%= link_to terrace.name, terrace_path(terrace) %></h5>
<p><%= terrace.address %></p>

app/views/terraces/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-second">

  <div class="d-flex justify-content-start">
    <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_tag terraces_path,class: "form-inline ml-3", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control mr-sm-2",
        type: "search",
        placeholder: "Ex: Bordeaux"
      %>
      <%= submit_tag "Search", class: "btn btn-outline-primary my-2 my-sm-0" %>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <% if !user_signed_in? %>
          <li class="nav-sec-item">
            <%= link_to "Host a terrace", user_session_path, class: "nav-sec-link" %>
          </li>
        <% else %>
          <li class="nav-sec-item">
            <%= link_to "Host a terrace", new_terrace_path, class: "nav-sec-link" %>
          </li>
        <% end %>
      <% if !user_signed_in? %>
        <div class="nav-sec-item">
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-sec-link" %>
          </li>
        </div>
        <div class='nav-sec-item'>
          <li>
            <%= link_to "Log in", user_session_path, class: "nav-sec-link" %>
          </li>
        </div>
      <% else %>
        <li class="nav-item dropdown d-flex align-items-center ml-3">
          <% if @user.avatar.attached? %>
            <img src="<%= (url_for(current_user.avatar)) %>" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true aria-expanded=false >
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My dashboard", bookings_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container-sm">
  <h2 class="mt-3">Find your sunny terrace</h2>
  <div class="row">

    <div class="col-sm-7">
      <div class="row">
      <% @terraces.each do |terrace| %>
        <div class="col-sm-4">
          <div class="card terrace my-3">
            <div style="width: 200px; height: 200px;">
              <%= cl_image_tag terrace.photo.key, class: "card-img-top terrace" %>
            </div>
            <div class="card-body terrace">
              <h5 class="card-title terrace"><%= link_to terrace.name, terrace_path(terrace) %></h5>
              <p class="card-text"><%= terrace.description %></p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="col-sm-5">
      <div
        id="map"
        class="bg-map"
        style="width: 100%;
        height: 95vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>

  </div>
  <div class =" mt-5 mb-5 d-flex justify-content-center">
  <%= link_to 'Back research', root_path, class: 'btn btn-sm btn-outline-primary' %>
  </div>
</div>

app/views/terraces/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-second">
  <%= link_to image_tag("logo.png"), root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <% if !user_signed_in? %>
          <li class="nav-sec-item">
            <%= link_to "Host a terrace", user_session_path, class: "nav-sec-link" %>
          </li>
        <% else %>
          <li class="nav-sec-item">
            <%= link_to "Host a terrace", new_terrace_path, class: "nav-sec-link" %>
          </li>
        <% end %>
      <% if !user_signed_in? %>
        <div class="nav-sec-item">
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-sec-link" %>
          </li>
        </div>
        <div class='nav-sec-item'>
          <li>
            <%= link_to "Log in", user_session_path, class: "nav-sec-link" %>
          </li>
        </div>
      <% else %>
        <li class="nav-item dropdown d-flex align-items-center ml-3">
          <% if @user.avatar.attached? %>
            <img src="<%= (url_for(current_user.avatar)) %>" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true aria-expanded=false >
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My dashboard", bookings_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <h2><%= @terrace.name %><span class="small"> - <%= @terrace.price_per_night %>€/night</span></h2>

  <div class="d-flex justify-content-center">
    <%= cl_image_tag @terrace.photo.key, class: "img-terrace" %>
  </div>

  <div id="wrapper">
    <div class="host-name">
      <h4><%= @terrace.user.name %></h4>
    </div>

    <div class="description">
      <%= @terrace.description %>
      <br>
      <br>
    </div>

    <div class="address">
      <em><%= @terrace.address %></em>
    </div>

    <!-- Button trigger modal -->
    <div class="check-dispo">
      <%= link_to 'Book this terrace', new_terrace_booking_path(@terrace), class: "btn btn-lg btn-primary", "data-toggle" => "modal", "data-target" => "#exampleModalCenter" %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLongTitle">Booking the terrace : <%= @terrace.name %></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class= "d-flex justify-content-center mt-5">
            <h5>Price per day: <%= @terrace.price_per_night %>€<h4>
          </div>

          <div class="modal-body d-flex justify-content-center text-center flex-column">
              <div class="widget-content" data-unavailable="<%= @terrace.unavailable_dates.to_json %>">
                <%= simple_form_for([@terrace, @booking]) do |f| %>
                  <%= f.input :start_date, as: :string, label: "From", placeholder: "pick a start date..", wrapper_html: { class: "inline_field_wrapper" } %>
                  <%= f.input :end_date, as: :string, label: "To",disabled: true, placeholder: "pick an end date..", wrapper_html: { class: "inline_field_wrapper" } %>
              </div>
          <!-- TEST PRIX -->
              <div class="costs costs-hidden" data-rate="<%= @terrace.price_per_night.to_json %>">
                <table class="table d-flex justify-content-center text-center">
                  <tr class="d-flex justify-content-center">
                    <td>€<%= @terrace.price_per_night %> x <span id="days">0</span> days</td>
                  </tr>
                  <tr>
                    <td><strong>Total</strong></td>
                    <td class="text-right">€<span id=total-price>0</span></td>
                  </tr>
                </table>
              </div>



          </div>

          <div class="modal-footer d-flex justify-content-center mt-2">
            <div class= "">
              <%= f.submit "Confirm", class: "btn btn-primary btn-lg btn-block btn-booking" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="container">
  <hr style="opacity: 0.6;">
</div>
<div
  id="map"
  class="bg-map mt-4"
  style="width: 100%;
  height: 70vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

<div class =" mt-5 mb-5 d-flex justify-content-center">
  <%= link_to 'Back to the list', terraces_path, class: 'btn btn-sm btn-outline-primary' %>
</div>

app/views/users/host.html.erb
<h2>Hote page</h2>
<p>page d'explication + bouton pour s'inscrire en tant qu'hôte</p>

app/views/users/show.html.erb
<h2>TODO: Dashboard User</h2>
<h4>My list of terraces</h4>
<ul>
<% @user.terraces.each do |terrace| %>
  <li>
    <%= terrace[:name] %> - 
    <%= link_to "Delete", user_terrace_path(terrace.user_id, terrace),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
  </li>
  <%= cl_image_tag terrace.photo.key %>
<% end %>
</ul>
<br>
<%= link_to 'New terrace', new_user_terrace_path(@user.id) %>